<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvxk3W6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvxk3W6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOvxk3W6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOvxk3W6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOvxk3W6\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ovxk3W6',
    'container.build_id' => '722a528f',
    'container.build_time' => 1690970036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvxk3W6');
