<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUuHulGS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUuHulGS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUuHulGS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUuHulGS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUuHulGS\App_KernelDevDebugContainer([
    'container.build_hash' => 'UuHulGS',
    'container.build_id' => '61b0e086',
    'container.build_time' => 1690970278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUuHulGS');
